name: pipeline-name-20240605

on:
  push:
    branches: [ "main" ]

jobs:

  Sample-Job-01:
    runs-on: ubuntu-latest       

    steps:
      - run: echo "Step without name tag"

      - name: Checkout Repo (With name tag)
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
    
        
  Sample-Job-02:
    runs-on: ubuntu-latest
    needs: Sample-Job-01

    steps:
      - run: echo "Step without name tag"

      - name: Checkout Repo (With name tag)
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
    
